import marimo

__generated_with = "unknown"
app = marimo.App()


@app.cell(hide_code=True)
def header(mo):
    mo.md(
        """
    # Data Inventory — Open Source AI Ecosystem

    Central inventory of all data sources used for the open-source AI ecosystem mapping.
    Loads and normalizes four sources: **Good AI List** (curated repo catalog),
    **OSS Insights AI Collections** (GitHub collection metadata),
    **OSAI Gap Map** (expert-scored maturity/parity ratings),
    and **OSO Projects** (Open Source Observer project registry).

    **Created:** 2026-04-27 · **Data:** OSO · Current AI · OSS Insights
    """
    )
    return


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def load_goodailist(mo, pyoso_db_conn):
    df_goodailist = mo.sql(
        f"""
        WITH ranked AS (
          SELECT
            LOWER(repo)                        AS repo,
            LOWER(SPLIT_PART(repo, '/', 1))    AS owner,
            SPLIT_PART(repo, '/', 2)           AS name,
            category,
            TRIM(SPLIT_PART(subcat, ',', 1))   AS primary_subcat,
            CAST(stars        AS DOUBLE)        AS stars,
            CAST(contributors AS DOUBLE)        AS contributors,
            language,
            ROW_NUMBER() OVER (
              PARTITION BY LOWER(repo)
              ORDER BY updated_at DESC NULLS LAST
            ) AS _rn
          FROM currentai.catalog.goodailist_repos
        )
        SELECT repo, owner, name, category, primary_subcat, stars, contributors, language
        FROM ranked
        WHERE _rn = 1
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_goodailist,)


@app.cell(hide_code=True)
def load_ossinsights(mo, pyoso_db_conn):
    df_ossinsights = mo.sql(
        f"""
        SELECT
          pc.collection_name,
          c.display_name AS collection_display_name,
          LOWER(a.artifact_namespace || '/' || a.artifact_name) AS repo
        FROM oso.oss_directory.projects_by_collection pc
        JOIN oso.oss_directory.collections c
          ON pc.collection_id = c.collection_id
        JOIN oso.oss_directory.artifacts_by_project a
          ON pc.project_id = a.project_id
          AND a.artifact_source = 'GITHUB'
        WHERE pc.collection_name LIKE 'ossinsight-%'
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_ossinsights,)


@app.cell(hide_code=True)
def load_osai_gap_map(pd):
    from pathlib import Path

    _data_dir = Path(__file__).parent.parent / "data"
    _csv_path = _data_dir / "osai-gap-map" / "scores.csv"

    _col_names = [
        "layer", "subcategory", "description", "subcategory_id",
        "breadth", "production_readiness", "ease_of_adoption",
        "documentation", "community_activity", "performance_vs_closed",
        "enterprise_readiness", "interoperability", "sustainability",
        "standardization", "criteria_avg", "overall_score",
        "maturity", "parity_verdict",
    ]

    df_gap_map = pd.read_csv(
        _csv_path,
        skiprows=2,
        names=_col_names,
    )
    return (df_gap_map,)


@app.cell(hide_code=True)
def load_oso_projects(mo, pyoso_db_conn):
    df_oso_projects = mo.sql(
        f"""
        SELECT
          p.project_id,
          p.project_name,
          p.display_name,
          a.artifact_namespace AS owner,
          a.artifact_name      AS name,
          LOWER(a.artifact_namespace || '/' || a.artifact_name) AS repo
        FROM oso.oss_directory.projects AS p
        JOIN oso.oss_directory.artifacts_by_project AS a
          ON p.project_id = a.project_id
        WHERE
          a.artifact_source = 'GITHUB'
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_oso_projects,)


@app.cell(hide_code=True)
def source_summary(df_goodailist, df_ossinsights, df_gap_map, df_oso_projects, mo):
    mo.hstack([
        mo.stat(
            value=len(df_goodailist),
            label="GoodAI List",
            caption=f"{df_goodailist['category'].nunique()} categories · {df_goodailist['primary_subcat'].nunique()} subcategories",
        ),
        mo.stat(
            value=df_ossinsights["repo"].nunique(),
            label="OSS Insights",
            caption=f"{df_ossinsights['collection_id'].nunique()} collections",
        ),
        mo.stat(
            value=len(df_gap_map),
            label="OSAI Gap Map",
            caption=f"{df_gap_map['layer'].nunique()} layers",
        ),
        mo.stat(
            value=df_oso_projects["repo"].nunique(),
            label="OSO Projects",
            caption=f"{df_oso_projects['project_id'].nunique()} projects",
        ),
    ])
    return


@app.cell(hide_code=True)
def overlap_analysis(df_goodailist, df_ossinsights, df_oso_projects, mo, pd):
    _goodai_repos = set(df_goodailist["repo"].dropna().unique())
    _ossi_repos = set(df_ossinsights["repo"].dropna().unique())
    _oso_repos = set(df_oso_projects["repo"].dropna().unique())

    _pairs = [
        ("GoodAI vs OSS Insights", _goodai_repos, _ossi_repos),
        ("GoodAI vs OSO", _goodai_repos, _oso_repos),
        ("OSS Insights vs OSO", _ossi_repos, _oso_repos),
    ]

    _overlap = pd.DataFrame([
        {
            "Source Pair": name,
            "Overlap": len(left & right),
            "Only Left": len(left - right),
            "Only Right": len(right - left),
        }
        for name, left, right in _pairs
    ])

    _all_repos = _goodai_repos | _ossi_repos | _oso_repos
    _in_two_plus = sum(
        1 for r in _all_repos
        if sum([r in _goodai_repos, r in _ossi_repos, r in _oso_repos]) >= 2
    )
    _in_all_three = len(_goodai_repos & _ossi_repos & _oso_repos)

    mo.vstack([
        mo.md(
            f"### Repo-Level Overlap\n\n"
            f"**{len(_all_repos):,}** unique repos across all sources · "
            f"**{_in_two_plus:,}** in 2+ sources · "
            f"**{_in_all_three:,}** in all 3"
        ),
        mo.ui.table(_overlap),
    ])
    return


@app.cell(hide_code=True)
def coverage_by_category(df_goodailist, df_oso_projects, go, mo, pd):
    _oso_repos = set(df_oso_projects["repo"].dropna().unique())

    _totals = df_goodailist.groupby("category")["repo"].nunique().reset_index(name="total")
    _in_oso = (
        df_goodailist[df_goodailist["repo"].isin(_oso_repos)]
        .groupby("category")["repo"]
        .nunique()
        .reset_index(name="in_oso")
    )
    _cov = _totals.merge(_in_oso, on="category", how="left").fillna(0)
    _cov["in_oso"] = _cov["in_oso"].astype(int)
    _cov = _cov.sort_values("total", ascending=True)

    _fig = go.Figure()
    _fig.add_trace(go.Bar(
        y=_cov["category"], x=_cov["total"],
        orientation="h", name="Total repos",
        marker_color="#c9bfac",
    ))
    _fig.add_trace(go.Bar(
        y=_cov["category"], x=_cov["in_oso"],
        orientation="h", name="In OSO",
        marker_color="#1b6b5e",
    ))
    _fig.update_layout(
        barmode="overlay",
        template="plotly_white",
        title="GoodAI Category Coverage in OSO",
        xaxis_title="Repos",
        yaxis_title="",
        margin=dict(l=200),
    )
    mo.ui.plotly(_fig)
    return


@app.cell(hide_code=True)
def osai_gap_map_summary(df_gap_map, go, mo, pd):
    _df = df_gap_map.copy()
    _df["overall_score"] = pd.to_numeric(_df["overall_score"], errors="coerce")
    _df = _df.dropna(subset=["overall_score"])

    if _df.empty:
        _result = mo.md("_No OSAI Gap Map data available._")
    else:
        _df["label"] = _df["layer"] + " · " + _df["subcategory"]
        _df = _df.sort_values("overall_score", ascending=True)

        _color_map = {1: "#c8341d", 2: "#d97c2a", 3: "#6b6253", 4: "#1b6b5e"}
        _colors = [_color_map.get(int(s), "#6b6253") for s in _df["overall_score"]]

        _dist = _df["overall_score"].astype(int).value_counts().sort_index()
        _dist_str = " · ".join(f"Score {int(k)}: {v}" for k, v in _dist.items())

        _fig = go.Figure(go.Bar(
            y=_df["label"], x=_df["overall_score"],
            orientation="h",
            marker_color=_colors,
        ))
        _fig.update_layout(
            template="plotly_white",
            title="OSAI Gap Map — Overall Scores",
            xaxis_title="Overall Score",
            yaxis_title="",
            margin=dict(l=300),
        )

        _result = mo.vstack([
            mo.md(f"### OSAI Gap Map Scores\n\n{_dist_str}"),
            mo.ui.plotly(_fig),
        ])
    _result
    return


if __name__ == "__main__":
    app.run()
