import marimo

__generated_with = "unknown"
app = marimo.App()


@app.cell(hide_code=True)
def header(mo):
    mo.md(
        """
        # Layer Mapping — Projects to OSAI Stack

        For each OSAI gap map subcategory, find the best-matching repos from the
        GoodAI List. This builds the curated shortlist that powers the website's
        stack view.

        **Approach:** Manual keyword mapping from OSAI subcategories → GoodAI
        (category, subcategory) pairs, then rank repos within each match by
        stars and contributor depth.
        """
    )
    return


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def load_osai(pd):
    from pathlib import Path
    _csv_path = Path(__file__).parent.parent / "data" / "osai-gap-map" / "scores.csv"
    df_osai = pd.read_csv(
        _csv_path,
        skiprows=1,
        names=[
            "layer", "subcategory", "description", "subcategory_id",
            "breadth", "production_readiness", "ease_of_adoption",
            "documentation", "community_activity", "performance_vs_closed",
            "enterprise_readiness", "interoperability", "sustainability",
            "standardization", "criteria_avg", "overall_score",
            "maturity", "parity_verdict",
        ],
    )
    df_osai = df_osai[df_osai['layer'] != 'Stack category']
    return (df_osai,)


@app.cell(hide_code=True)
def load_repos(mo, pyoso_db_conn):
    df_repos = mo.sql(
        f"""
        WITH ranked AS (
          SELECT
            LOWER(repo) AS repo,
            LOWER(SPLIT_PART(repo, '/', 1)) AS owner,
            category,
            TRIM(SPLIT_PART(subcat, ',', 1)) AS subcategory,
            CAST(stars AS BIGINT) AS stars,
            CAST(contributors AS BIGINT) AS contributors,
            language,
            country,
            description,
            ROW_NUMBER() OVER (
              PARTITION BY LOWER(repo)
              ORDER BY updated_at DESC NULLS LAST
            ) AS _rn
          FROM currentai.goodailist_repos.repos
        )
        SELECT repo, owner, category, subcategory, stars, contributors, language, country, description
        FROM ranked
        WHERE _rn = 1
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_repos,)


@app.cell(hide_code=True)
def layer_mapping():
    OSAI_TO_GOODAI = {
        ("Infrastructure", "Cloud Compute"): [
            ("Infrastructure", "Deploy & Serve"),
            ("Infrastructure", "Orchestration"),
        ],
        ("Infrastructure", "Communication Libs"): [
            ("Infrastructure", "Orchestration"),
            ("Model Development", "Training toolkits"),
        ],
        ("Infrastructure", "Compilers"): [
            ("Infrastructure", "Kernels"),
            ("Infrastructure", "Model optimization"),
        ],
        ("Infrastructure", "Firmware Drivers"): [
            ("Infrastructure", "Kernels"),
        ],
        ("Infrastructure", "Hardware Chips"): [
            ("Infrastructure", "Kernels"),
        ],
        ("Infrastructure", "Ml Frameworks"): [
            ("Model Development", "Deep Learning Frameworks"),
            ("Model Development", "Architecture"),
        ],
        ("Infrastructure", "Storage"): [
            ("Infrastructure", "Data systems"),
            ("AI Engineering", "Give agent knowledge"),
        ],
        ("Model Components: Datasets", "Benchmark Eval Data"): [
            ("AI Engineering", "Test & guard"),
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Datasets", "Data Preprocessing"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Datasets", "Preference Alignment Data"): [
            ("Model Development", "Fine-tuning"),
            ("Model Development", "Reinforcement Learning"),
        ],
        ("Model Components: Datasets", "Pretraining Data"): [
            ("Model Development", "Dataset engineering"),
            ("Model Development", "LLM training"),
        ],
        ("Model Components: Datasets", "Synthetic Data"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Code", "Evaluation Code"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Model Components: Code", "Finetuning Code"): [
            ("Model Development", "Fine-tuning"),
        ],
        ("Model Components: Code", "Inference Code"): [
            ("Infrastructure", "Inference service optimization"),
            ("Infrastructure", "Deploy & Serve"),
        ],
        ("Model Components: Code", "Model Architecture"): [
            ("Model Development", "Architecture"),
        ],
        ("Model Components: Code", "Supporting Libraries"): [
            ("Model Development", "Training toolkits"),
            ("Model Development", "Deep Learning Frameworks"),
        ],
        ("Model Components: Code", "Training Code"): [
            ("Model Development", "LLM training"),
            ("Model Development", "Training toolkits"),
        ],
        ("Model Components: Weights", "Base Pretrained"): [
            ("Models", "Foundation models"),
        ],
        ("Model Components: Weights", "Compressed Weights"): [
            ("Infrastructure", "Model optimization"),
            ("Models", "Foundation models"),
        ],
        ("Model Components: Weights", "Domain Weights"): [
            ("Models", "Domain-specific models"),
        ],
        ("Model Components: Weights", "Finetuned Chat"): [
            ("Models", "Foundation models"),
            ("Models", "Language-specific models"),
        ],
        ("Model Components: Weights", "Multimodal Weights"): [
            ("Models", "Vision models"),
            ("Models", "Audio/Speech models"),
        ],
        ("Product / UX", "Deployment"): [
            ("Infrastructure", "Deploy & Serve"),
        ],
        ("Product / UX", "Orchestration Agents"): [
            ("AI Engineering", "Build agent workflow (SDK)"),
            ("AI Engineering", "Build agent workflow (visual)"),
        ],
        ("Product / UX", "Output Settings"): [
            ("AI Engineering", "Prompt & Scaffold"),
            ("AI Engineering", "Access models"),
        ],
        ("Product / UX", "System Prompt"): [
            ("AI Engineering", "Prompt & Scaffold"),
        ],
        ("Product / UX", "Telemetry Observability"): [
            ("Infrastructure", "Observability"),
        ],
        ("Product / UX", "Ui Api"): [
            ("AI Engineering", "Build agent UI"),
            ("AI Engineering", "Bring agent to users"),
        ],
        ("Documentation", "Data Documentation"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Documentation", "Eval Results"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Documentation", "Model Cards"): [
            ("Models", "Foundation models"),
        ],
        ("Documentation", "Sample Outputs Demos"): [
            ("AI Engineering", "Build agent UI"),
            ("Applications", "Content creation"),
        ],
        ("Licensing", "Code Licenses"): [],
        ("Licensing", "Dataset Licenses"): [],
        ("Licensing", "Terms Of Service"): [],
        ("Licensing", "Weight Licenses"): [],
        ("Safeguards", "Access Release"): [],
        ("Safeguards", "Auditing Reporting"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Safeguards", "Governance"): [],
        ("Safeguards", "Moderation"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Safeguards", "Safety Alignment"): [
            ("Model Development", "Reinforcement Learning"),
        ],
    }
    return (OSAI_TO_GOODAI,)


@app.cell(hide_code=True)
def mapping_coverage(OSAI_TO_GOODAI, df_osai, mo, pd):
    _rows = []
    for _, osai_row in df_osai.iterrows():
        _key = (osai_row['layer'], osai_row['subcategory'])
        _goodai_matches = OSAI_TO_GOODAI.get(_key, [])
        _rows.append({
            'OSAI Layer': osai_row['layer'],
            'OSAI Subcategory': osai_row['subcategory'],
            'Score': osai_row['overall_score'],
            'Maturity': osai_row['maturity'],
            'GoodAI Matches': len(_goodai_matches),
            'GoodAI Mapping': '; '.join(f'{c} / {s}' for c, s in _goodai_matches) if _goodai_matches else '(unmapped)',
        })

    df_coverage = pd.DataFrame(_rows)
    _mapped = (df_coverage['GoodAI Matches'] > 0).sum()
    _total = len(df_coverage)

    mo.vstack([
        mo.md(
            f"## Mapping Coverage\n\n"
            f"**{_mapped}/{_total}** OSAI subcategories mapped to GoodAI. "
            f"Unmapped ones are cross-cutting (Licensing, Safeguards) that don't map "
            f"directly to repo categories."
        ),
        mo.ui.table(df_coverage, show_column_summaries=False, show_data_types=False),
    ])
    return (df_coverage,)


@app.cell(hide_code=True)
def layer_selector(df_osai, mo):
    _layers = sorted(df_osai['layer'].unique().tolist())
    layer_dropdown = mo.ui.dropdown(
        options=_layers,
        value=_layers[0],
        label="Select OSAI Layer",
    )
    layer_dropdown
    return (layer_dropdown,)


@app.cell(hide_code=True)
def subcat_selector(df_osai, layer_dropdown, mo):
    _subcats = df_osai[df_osai['layer'] == layer_dropdown.value]['subcategory'].tolist()
    subcat_dropdown = mo.ui.dropdown(
        options=_subcats,
        value=_subcats[0] if _subcats else None,
        label="Select Subcategory",
    )
    subcat_dropdown
    return (subcat_dropdown,)


@app.cell(hide_code=True)
def selected_projects(OSAI_TO_GOODAI, df_osai, df_repos, layer_dropdown, mo, pd, subcat_dropdown):
    _key = (layer_dropdown.value, subcat_dropdown.value)
    _osai_row = df_osai[(df_osai['layer'] == _key[0]) & (df_osai['subcategory'] == _key[1])]
    _goodai_matches = OSAI_TO_GOODAI.get(_key, [])

    if not _goodai_matches:
        mo.vstack([
            mo.md(f"## {_key[0]} · {_key[1]}"),
            mo.md(f"**Score:** {_osai_row.iloc[0]['overall_score']} · **Maturity:** {_osai_row.iloc[0]['maturity']}" if len(_osai_row) > 0 else ""),
            mo.md("_No GoodAI mapping — this is a cross-cutting category (Licensing, Safeguards, Documentation)._"),
        ])
        return

    _mask = pd.Series(False, index=df_repos.index)
    for _cat, _sub in _goodai_matches:
        _mask = _mask | ((df_repos['category'] == _cat) & (df_repos['subcategory'] == _sub))

    _matched = df_repos[_mask].nlargest(30, 'stars')[
        ['repo', 'category', 'subcategory', 'stars', 'contributors', 'language', 'country']
    ].copy()
    _matched['stars'] = _matched['stars'].apply(lambda x: f"{x:,}")
    _matched.columns = ['Repository', 'GoodAI Category', 'GoodAI Subcategory', 'Stars', 'Contributors', 'Language', 'Country']
    _matched = _matched.reset_index(drop=True)

    _desc = _osai_row.iloc[0]['description'] if len(_osai_row) > 0 else ''
    _score = _osai_row.iloc[0]['overall_score'] if len(_osai_row) > 0 else ''
    _maturity = _osai_row.iloc[0]['maturity'] if len(_osai_row) > 0 else ''
    _parity = _osai_row.iloc[0]['parity_verdict'] if len(_osai_row) > 0 else ''

    mo.vstack([
        mo.md(f"## {_key[0]} · {_key[1]}"),
        mo.md(f"_{_desc}_"),
        mo.hstack([
            mo.stat(value=_score, label="Score", bordered=True),
            mo.stat(value=_maturity, label="Maturity", bordered=True),
            mo.stat(value=_parity, label="vs Closed", bordered=True),
            mo.stat(value=len(df_repos[_mask]), label="Total Repos", bordered=True),
        ]),
        mo.md(f"**Mapped from:** {', '.join(f'{c} / {s}' for c, s in _goodai_matches)}"),
        mo.md("### Top 30 Projects"),
        mo.ui.table(_matched, show_column_summaries=False, show_data_types=False),
    ])
    return


if __name__ == "__main__":
    app.run()
