import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "Fraunces, Georgia, serif",
        "body": "Inter, -apple-system, system-ui, sans-serif",
        "mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#1a1814",
        "ink_2": "#3a342b",
        "ink_3": "#6b6253",
        "paper": "#f5f1ea",
        "paper_2": "#ede7dc",
        "rule": "#c9bfac",
        "signal": "#c8341d",
        "healthy": "#1b6b5e",
        "healthy_soft": "#6ba99a",
        "warm": "#d97c2a",
        "accent": "#2a3d8f",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=20, l=60, r=20, b=50),
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=11),
            orientation="h",
            yanchor="bottom", y=1.02,
            xanchor="left", x=0,
        ),
        hovermode="closest",
    )
    CHART_LAYOUT = LAYOUT
    CAT_COLORS = {
        "Infrastructure": "#1A5276",
        "AI Engineering": "#196F3D",
        "Model Development": "#922B21",
        "Applications": "#6C3483",
        "Models": "#117A65",
        "Tutorials": "#784212",
        "Lists": "#17202A",
        "Misc": "#717D7E",
    }
    return C, CAT_COLORS, CHART_LAYOUT, F, LAYOUT


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:36px;">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:10px;">'
        f'Current AI · Ecosystem Mapping · Layer Explorer</div>'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.2rem; font-weight:400; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'Projects by OSAI Stack Layer</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.5;">'
        f'For each OSAI gap map subcategory, find the best-matching repos from the '
        f'GoodAI List. Select a layer and subcategory to explore top projects.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_osai(pd):
    from pathlib import Path
    _csv_path = Path(__file__).parent.parent / "data" / "osai-gap-map" / "scores.csv"
    df_osai = pd.read_csv(
        _csv_path,
        skiprows=1,
        names=[
            "layer", "subcategory", "description", "subcategory_id",
            "breadth", "production_readiness", "ease_of_adoption",
            "documentation", "community_activity", "performance_vs_closed",
            "enterprise_readiness", "interoperability", "sustainability",
            "standardization", "criteria_avg", "overall_score",
            "maturity", "parity_verdict",
        ],
    )
    df_osai = df_osai[df_osai['layer'] != 'Stack category']
    return (df_osai,)


@app.cell(hide_code=True)
def load_repos(mo, pyoso_db_conn):
    df_repos = mo.sql(
        f"""
        WITH ranked AS (
          SELECT
            LOWER(repo) AS repo,
            LOWER(SPLIT_PART(repo, '/', 1)) AS owner,
            category,
            TRIM(SPLIT_PART(subcat, ',', 1)) AS subcategory,
            CAST(stars AS BIGINT) AS stars,
            CAST(contributors AS BIGINT) AS contributors,
            language,
            country,
            description,
            ROW_NUMBER() OVER (
              PARTITION BY LOWER(repo)
              ORDER BY updated_at DESC NULLS LAST
            ) AS _rn
          FROM currentai.goodailist_repos.repos
        )
        SELECT repo, owner, category, subcategory, stars, contributors, language, country, description
        FROM ranked
        WHERE _rn = 1
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_repos,)


@app.cell(hide_code=True)
def osai_to_goodai_mapping():
    OSAI_TO_GOODAI = {
        ("Infrastructure", "Cloud Compute"): [
            ("Infrastructure", "Deploy & Serve"),
            ("Infrastructure", "Orchestration"),
        ],
        ("Infrastructure", "Communication Libs"): [
            ("Infrastructure", "Orchestration"),
            ("Model Development", "Training toolkits"),
        ],
        ("Infrastructure", "Compilers"): [
            ("Infrastructure", "Kernels"),
            ("Infrastructure", "Model optimization"),
        ],
        ("Infrastructure", "Firmware Drivers"): [
            ("Infrastructure", "Kernels"),
        ],
        ("Infrastructure", "Hardware Chips"): [
            ("Infrastructure", "Kernels"),
        ],
        ("Infrastructure", "Ml Frameworks"): [
            ("Model Development", "Deep Learning Frameworks"),
            ("Model Development", "Architecture"),
        ],
        ("Infrastructure", "Storage"): [
            ("Infrastructure", "Data systems"),
            ("AI Engineering", "Give agent knowledge"),
        ],
        ("Model Components: Datasets", "Benchmark Eval Data"): [
            ("AI Engineering", "Test & guard"),
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Datasets", "Data Preprocessing"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Datasets", "Preference Alignment Data"): [
            ("Model Development", "Fine-tuning"),
            ("Model Development", "Reinforcement Learning"),
        ],
        ("Model Components: Datasets", "Pretraining Data"): [
            ("Model Development", "Dataset engineering"),
            ("Model Development", "LLM training"),
        ],
        ("Model Components: Datasets", "Synthetic Data"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Model Components: Code", "Evaluation Code"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Model Components: Code", "Finetuning Code"): [
            ("Model Development", "Fine-tuning"),
        ],
        ("Model Components: Code", "Inference Code"): [
            ("Infrastructure", "Inference service optimization"),
            ("Infrastructure", "Deploy & Serve"),
        ],
        ("Model Components: Code", "Model Architecture"): [
            ("Model Development", "Architecture"),
        ],
        ("Model Components: Code", "Supporting Libraries"): [
            ("Model Development", "Training toolkits"),
            ("Model Development", "Deep Learning Frameworks"),
        ],
        ("Model Components: Code", "Training Code"): [
            ("Model Development", "LLM training"),
            ("Model Development", "Training toolkits"),
        ],
        ("Model Components: Weights", "Base Pretrained"): [
            ("Models", "Foundation models"),
        ],
        ("Model Components: Weights", "Compressed Weights"): [
            ("Infrastructure", "Model optimization"),
            ("Models", "Foundation models"),
        ],
        ("Model Components: Weights", "Domain Weights"): [
            ("Models", "Domain-specific models"),
        ],
        ("Model Components: Weights", "Finetuned Chat"): [
            ("Models", "Foundation models"),
            ("Models", "Language-specific models"),
        ],
        ("Model Components: Weights", "Multimodal Weights"): [
            ("Models", "Vision models"),
            ("Models", "Audio/Speech models"),
        ],
        ("Product / UX", "Deployment"): [
            ("Infrastructure", "Deploy & Serve"),
        ],
        ("Product / UX", "Orchestration Agents"): [
            ("AI Engineering", "Build agent workflow (SDK)"),
            ("AI Engineering", "Build agent workflow (visual)"),
        ],
        ("Product / UX", "Output Settings"): [
            ("AI Engineering", "Prompt & Scaffold"),
            ("AI Engineering", "Access models"),
        ],
        ("Product / UX", "System Prompt"): [
            ("AI Engineering", "Prompt & Scaffold"),
        ],
        ("Product / UX", "Telemetry Observability"): [
            ("Infrastructure", "Observability"),
        ],
        ("Product / UX", "Ui Api"): [
            ("AI Engineering", "Build agent UI"),
            ("AI Engineering", "Bring agent to users"),
        ],
        ("Documentation", "Data Documentation"): [
            ("Model Development", "Dataset engineering"),
        ],
        ("Documentation", "Eval Results"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Documentation", "Model Cards"): [
            ("Models", "Foundation models"),
        ],
        ("Documentation", "Sample Outputs Demos"): [
            ("AI Engineering", "Build agent UI"),
            ("Applications", "Content creation"),
        ],
        ("Licensing", "Code Licenses"): [],
        ("Licensing", "Dataset Licenses"): [],
        ("Licensing", "Terms Of Service"): [],
        ("Licensing", "Weight Licenses"): [],
        ("Safeguards", "Access Release"): [],
        ("Safeguards", "Auditing Reporting"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Safeguards", "Governance"): [],
        ("Safeguards", "Moderation"): [
            ("AI Engineering", "Test & guard"),
        ],
        ("Safeguards", "Safety Alignment"): [
            ("Model Development", "Reinforcement Learning"),
        ],
    }
    return (OSAI_TO_GOODAI,)


@app.cell(hide_code=True)
def health_color_fn(C):
    def health_color(score):
        try:
            _s = float(score)
        except (ValueError, TypeError):
            return C["ink_3"]
        if _s >= 4:
            return C["healthy"]
        elif _s >= 3:
            return C["warm"]
        return C["signal"]
    return (health_color,)


@app.cell(hide_code=True)
def mapping_coverage(C, F, OSAI_TO_GOODAI, df_osai, go, health_color, mo, pd):
    _rows = []
    for _, _osai_row in df_osai.iterrows():
        _key = (_osai_row['layer'], _osai_row['subcategory'])
        _goodai_matches = OSAI_TO_GOODAI.get(_key, [])
        _rows.append({
            'layer': _osai_row['layer'],
            'subcategory': _osai_row['subcategory'],
            'score': _osai_row['overall_score'],
            'maturity': _osai_row['maturity'],
            'n_matches': len(_goodai_matches),
        })

    _df = pd.DataFrame(_rows)
    _df = _df.sort_values('score', ascending=True)

    _fig = go.Figure(go.Bar(
        y=_df['layer'] + ' · ' + _df['subcategory'],
        x=_df['score'],
        orientation='h',
        marker_color=[health_color(s) for s in _df['score']],
        customdata=list(zip(_df['maturity'], _df['n_matches'])),
        hovertemplate=(
            '<b>%{y}</b><br>'
            'Score: %{x}<br>'
            'Maturity: %{customdata[0]}<br>'
            'GoodAI mappings: %{customdata[1]}'
            '<extra></extra>'
        ),
    ))
    _fig.update_layout(
        plot_bgcolor='white',
        paper_bgcolor='white',
        font=dict(family=F['body'], size=11, color=C['ink']),
        margin=dict(t=10, l=0, r=30, b=40),
        height=max(400, len(_df) * 24),
        xaxis=dict(title='Overall Score (1–4)', dtick=1, range=[0, 5],
                   showgrid=True, gridcolor=C['rule']),
        yaxis=dict(title='', showgrid=False),
    )

    _mapped = (_df['n_matches'] > 0).sum()
    mo.vstack([
        mo.md(
            f'## Mapping Coverage\n\n'
            f'**{_mapped}/{len(_df)}** OSAI subcategories mapped to GoodAI repos. '
            f'Health color: '
            f'<span style="color:{C["healthy"]}">■</span> strong (4), '
            f'<span style="color:{C["warm"]}">■</span> viable (3), '
            f'<span style="color:{C["signal"]}">■</span> early/gap (≤2).'
        ),
        mo.ui.plotly(_fig),
    ])
    return


@app.cell(hide_code=True)
def layer_selector(df_osai, mo):
    _layers = sorted(df_osai['layer'].unique().tolist())
    layer_dropdown = mo.ui.dropdown(
        options=_layers,
        value=_layers[0],
        label="Select OSAI Layer",
    )
    layer_dropdown
    return (layer_dropdown,)


@app.cell(hide_code=True)
def subcat_selector(df_osai, layer_dropdown, mo):
    _subcats = df_osai[df_osai['layer'] == layer_dropdown.value]['subcategory'].tolist()
    subcat_dropdown = mo.ui.dropdown(
        options=_subcats,
        value=_subcats[0] if _subcats else None,
        label="Select Subcategory",
    )
    subcat_dropdown
    return (subcat_dropdown,)


@app.cell(hide_code=True)
def selected_projects(C, CAT_COLORS, F, LAYOUT, OSAI_TO_GOODAI, df_osai, df_repos, go, health_color, layer_dropdown, mo, pd, subcat_dropdown):
    _key = (layer_dropdown.value, subcat_dropdown.value)
    _osai_row = df_osai[(df_osai['layer'] == _key[0]) & (df_osai['subcategory'] == _key[1])]
    _goodai_matches = OSAI_TO_GOODAI.get(_key, [])

    _desc = _osai_row.iloc[0]['description'] if len(_osai_row) > 0 else ''
    _score = _osai_row.iloc[0]['overall_score'] if len(_osai_row) > 0 else ''
    _maturity = _osai_row.iloc[0]['maturity'] if len(_osai_row) > 0 else ''
    _parity = _osai_row.iloc[0]['parity_verdict'] if len(_osai_row) > 0 else ''
    _score_color = health_color(_score)

    _header = mo.Html(
        f'<div style="margin:20px 0 24px;">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'{_key[0]}</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.5rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 8px; letter-spacing:-0.015em;">{_key[1]}</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.5;">{_desc}</p>'
        f'</div>'
    )

    _stats = mo.hstack([
        mo.stat(value=str(_score), label="Score", bordered=True, caption=f'<span style="color:{_score_color}">●</span> {_maturity}'),
        mo.stat(value=str(_parity), label="vs Closed Source", bordered=True),
    ], widths="equal", gap=1)

    if not _goodai_matches:
        _output = mo.vstack([
            _header,
            _stats,
            mo.md("_No GoodAI mapping — this is a cross-cutting category (Licensing, Safeguards)._"),
        ])
    else:
        _mask = pd.Series(False, index=df_repos.index)
        for _cat, _sub in _goodai_matches:
            _mask = _mask | ((df_repos['category'] == _cat) & (df_repos['subcategory'] == _sub))

        _total_repos = int(_mask.sum())
        _top = df_repos[_mask].nlargest(30, 'stars').copy()

        _fig = go.Figure(go.Bar(
            y=_top['repo'],
            x=_top['stars'],
            orientation='h',
            marker_color=[CAT_COLORS.get(c, C['ink_3']) for c in _top['category']],
            customdata=list(zip(_top['category'], _top['contributors'], _top['language'], _top['country'].fillna(''))),
            hovertemplate=(
                '<b>%{y}</b><br>'
                'Stars: %{x:,}<br>'
                'Category: %{customdata[0]}<br>'
                'Contributors: %{customdata[1]}<br>'
                'Language: %{customdata[2]}<br>'
                'Country: %{customdata[3]}'
                '<extra></extra>'
            ),
        ))
        _fig.update_layout(
            **LAYOUT,
            height=max(300, len(_top) * 28),
            xaxis=dict(title='Stars', showgrid=True, gridcolor=C['rule']),
            yaxis=dict(title='', showgrid=False),
        )

        _mapped_label = ', '.join(f'{c} / {s}' for c, s in _goodai_matches)

        _output = mo.vstack([
            _header,
            mo.hstack([
                mo.stat(value=str(_score), label="Score", bordered=True, caption=f'{_maturity}'),
                mo.stat(value=str(_parity), label="vs Closed", bordered=True),
                mo.stat(value=f"{_total_repos:,}", label="Total Repos", bordered=True),
            ], widths="equal", gap=1),
            mo.md(f'**Mapped from:** {_mapped_label}'),
            mo.ui.plotly(_fig),
        ])
    _output


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:44px; padding-top:20px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:10px; color:{C["ink_3"]}; '
        f'letter-spacing:0.08em; text-transform:uppercase; margin-bottom:8px;">Methodology</div>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
        f'line-height:1.5;">'
        f'OSAI gap map scores (1–4) are qualitative expert assessments across 10 dimensions. '
        f'GoodAI List repos are matched via a manual mapping from OSAI subcategories to '
        f'GoodAI (category, subcategory) pairs. Repos ranked by star count as a proxy for adoption. '
        f'Licensing and Safeguards layers are cross-cutting and do not map to specific repos.</p>'
        f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; margin-top:8px;">'
        f'<strong>Source:</strong> '
        f'<a href="https://www.oso.xyz" style="color:{C["accent"]}">Open Source Observer</a> · '
        f'<a href="https://goodailist.com" style="color:{C["accent"]}">GoodAI List</a></p>'
        f'</div>'
    )
    return


if __name__ == "__main__":
    app.run()
