import marimo

__generated_with = "unknown"
app = marimo.App()


@app.cell(hide_code=True)
def header(mo):
    mo.md(
        """
        # Taxonomy Mapping — OSAI Gap Map × GoodAI List

        Exploring the overlap between the two classification systems to build
        a mapping from the OSAI gap map's editorial taxonomy (7 layers, 41 subcategories)
        to the GoodAI List's repo-level data (8 categories, 284 subcategories).

        **Goal:** For each OSAI subcategory, find the best-matching GoodAI subcategories
        so we can populate the website's stack view with real project data.
        """
    )
    return


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go
    return go, pd


@app.cell(hide_code=True)
def load_osai_gap_map(pd):
    from pathlib import Path
    _csv_path = Path(__file__).parent.parent / "data" / "osai-gap-map" / "scores.csv"
    df_osai = pd.read_csv(
        _csv_path,
        skiprows=1,
        names=[
            "layer", "subcategory", "description", "subcategory_id",
            "breadth", "production_readiness", "ease_of_adoption",
            "documentation", "community_activity", "performance_vs_closed",
            "enterprise_readiness", "interoperability", "sustainability",
            "standardization", "criteria_avg", "overall_score",
            "maturity", "parity_verdict",
        ],
    )
    return (df_osai,)


@app.cell(hide_code=True)
def load_goodai_subcats(mo, pyoso_db_conn):
    df_goodai_subcats = mo.sql(
        f"""
        WITH ranked AS (
          SELECT
            LOWER(repo) AS repo,
            category,
            subcategory,
            CAST(stars AS BIGINT) AS stars,
            CAST(contributors AS BIGINT) AS contributors,
            ROW_NUMBER() OVER (
              PARTITION BY LOWER(repo)
              ORDER BY updated_at DESC NULLS LAST
            ) AS _rn
          FROM currentai.scores.repos_summary
        )
        SELECT
          category,
          subcategory,
          COUNT(*) AS repos,
          SUM(stars) AS total_stars,
          CAST(APPROX_PERCENTILE(CAST(stars AS DOUBLE), 0.5) AS BIGINT) AS median_stars,
          CAST(APPROX_PERCENTILE(CAST(contributors AS DOUBLE), 0.5) AS BIGINT) AS median_contributors
        FROM ranked
        WHERE _rn = 1
        GROUP BY category, subcategory
        ORDER BY category, repos DESC
        """,
        output=False,
        engine=pyoso_db_conn
    )
    return (df_goodai_subcats,)


@app.cell(hide_code=True)
def osai_overview(df_osai, mo):
    _by_layer = df_osai.groupby('layer').agg(
        subcats=('subcategory', 'count'),
        avg_score=('overall_score', 'mean'),
    ).reset_index().sort_values('subcats', ascending=False)
    _by_layer['avg_score'] = _by_layer['avg_score'].round(1)
    _by_layer.columns = ['Layer', 'Subcategories', 'Avg Score']

    mo.vstack([
        mo.md(f"## OSAI Gap Map — {len(df_osai)} subcategories across {df_osai['layer'].nunique()} layers"),
        mo.ui.table(_by_layer, show_column_summaries=False, show_data_types=False),
    ])
    return


@app.cell(hide_code=True)
def goodai_overview(df_goodai_subcats, mo):
    _by_cat = df_goodai_subcats.groupby('category').agg(
        subcats=('subcategory', 'nunique'),
        total_repos=('repos', 'sum'),
    ).reset_index().sort_values('total_repos', ascending=False)
    _by_cat.columns = ['Category', 'Subcategories', 'Total Repos']

    mo.vstack([
        mo.md(f"## GoodAI List — {df_goodai_subcats['subcategory'].nunique()} subcategories across {df_goodai_subcats['category'].nunique()} categories"),
        mo.ui.table(_by_cat, show_column_summaries=False, show_data_types=False),
    ])
    return


@app.cell(hide_code=True)
def keyword_overlap(df_goodai_subcats, df_osai, mo, pd):
    _osai_terms = []
    for _, row in df_osai.iterrows():
        _terms = set()
        for field in ['subcategory', 'description']:
            if pd.notna(row[field]):
                _terms.update(w.lower() for w in str(row[field]).split() if len(w) > 2)
        _osai_terms.append({
            'layer': row['layer'],
            'subcategory': row['subcategory'],
            'overall_score': row['overall_score'],
            'terms': _terms,
        })

    _matches = []
    for osai in _osai_terms:
        for _, gai in df_goodai_subcats.iterrows():
            _gai_terms = set(w.lower() for w in str(gai['subcategory']).split() if len(w) > 2)
            _overlap = osai['terms'] & _gai_terms
            if _overlap:
                _matches.append({
                    'OSAI Layer': osai['layer'],
                    'OSAI Subcategory': osai['subcategory'],
                    'OSAI Score': osai['overall_score'],
                    'GoodAI Category': gai['category'],
                    'GoodAI Subcategory': gai['subcategory'],
                    'GoodAI Repos': gai['repos'],
                    'Matching Terms': ', '.join(sorted(_overlap)),
                })

    df_matches = pd.DataFrame(_matches)
    df_matches = df_matches.sort_values(['OSAI Layer', 'OSAI Subcategory', 'GoodAI Repos'], ascending=[True, True, False])

    _matched_osai = df_matches['OSAI Subcategory'].nunique()
    _total_osai = len(df_osai)

    mo.vstack([
        mo.md(
            f"## Keyword Overlap\n\n"
            f"Simple term matching between OSAI subcategory names/descriptions and GoodAI subcategory names.\n\n"
            f"**{_matched_osai}/{_total_osai}** OSAI subcategories have at least one keyword match. "
            f"**{_total_osai - _matched_osai}** have no match and will need manual mapping."
        ),
        mo.ui.table(df_matches, show_column_summaries=False, show_data_types=False),
    ])
    return (df_matches,)


@app.cell(hide_code=True)
def unmatched_osai(df_matches, df_osai, mo, pd):
    _matched = set(df_matches['OSAI Subcategory'].unique()) if not df_matches.empty else set()
    _unmatched = df_osai[~df_osai['subcategory'].isin(_matched)][
        ['layer', 'subcategory', 'description', 'overall_score', 'maturity']
    ].copy()
    _unmatched.columns = ['Layer', 'Subcategory', 'Description', 'Score', 'Maturity']

    mo.vstack([
        mo.md(
            f"## Unmatched OSAI Subcategories\n\n"
            f"**{len(_unmatched)}** subcategories with no keyword match to GoodAI — "
            f"these need manual mapping or may represent genuine gaps in the GoodAI taxonomy."
        ),
        mo.ui.table(_unmatched, show_column_summaries=False, show_data_types=False),
    ])
    return


@app.cell(hide_code=True)
def side_by_side(df_goodai_subcats, df_osai, mo):
    _osai_list = df_osai[['layer', 'subcategory', 'overall_score']].copy()
    _osai_list.columns = ['Layer', 'Subcategory', 'Score']
    _osai_list = _osai_list.sort_values(['Layer', 'Subcategory'])

    _goodai_list = df_goodai_subcats[['category', 'subcategory', 'repos']].copy()
    _goodai_list.columns = ['Category', 'Subcategory', 'Repos']
    _goodai_list = _goodai_list.sort_values(['Category', 'Subcategory'])

    mo.vstack([
        mo.md("## Side-by-Side Reference"),
        mo.hstack([
            mo.vstack([
                mo.md("### OSAI Gap Map"),
                mo.ui.table(_osai_list, show_column_summaries=False, show_data_types=False),
            ]),
            mo.vstack([
                mo.md("### GoodAI List"),
                mo.ui.table(_goodai_list, show_column_summaries=False, show_data_types=False),
            ]),
        ]),
    ])
    return


if __name__ == "__main__":
    app.run()
