import marimo

__generated_with = "unknown"
app = marimo.App(width="full")


@app.cell(hide_code=True)
def setup_pyoso():
    # This code sets up pyoso to be used as a database provider for this notebook
    # This code is autogenerated. Modification could lead to unexpected results :)
    import pyoso
    import marimo as mo
    pyoso_db_conn = pyoso.Client().dbapi_connection()
    return mo, pyoso_db_conn


@app.cell(hide_code=True)
def imports():
    import pandas as pd
    import plotly.graph_objects as go

    return (go,)


@app.cell(hide_code=True)
def style():
    F = {
        "headline": "Fraunces, Georgia, serif",
        "body": "Inter, -apple-system, system-ui, sans-serif",
        "mono": "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
    }
    C = {
        "ink": "#1a1814",
        "ink_2": "#3a342b",
        "ink_3": "#6b6253",
        "paper": "#f5f1ea",
        "paper_2": "#ede7dc",
        "rule": "#c9bfac",
        "signal": "#c8341d",
        "signal_soft": "#e98a78",
        "healthy": "#1b6b5e",
        "healthy_soft": "#6ba99a",
        "warm": "#d97c2a",
        "accent": "#2a3d8f",
    }
    LAYOUT = dict(
        plot_bgcolor="white",
        paper_bgcolor="white",
        font=dict(family=F["body"], size=12, color=C["ink"]),
        margin=dict(t=20, l=60, r=20, b=50),
        legend=dict(
            bgcolor="rgba(0,0,0,0)",
            font=dict(size=11),
            orientation="h",
            yanchor="bottom", y=1.02,
            xanchor="left", x=0,
        ),
        hovermode="closest",
    )
    CHART_LAYOUT = LAYOUT
    CAT_COLORS = {
        "Infrastructure": "#1A5276",
        "AI Engineering": "#196F3D",
        "Model Development": "#922B21",
        "Applications": "#6C3483",
        "Models": "#117A65",
        "Tutorials": "#784212",
        "Lists": "#17202A",
        "Misc": "#717D7E",
    }
    return C, CAT_COLORS, CHART_LAYOUT, F


@app.cell(hide_code=True)
def fonts(mo):
    mo.Html(
        '<style>'
        '@import url("https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap");'
        '</style>'
    )
    return


@app.cell(hide_code=True)
def header(C, F, mo):
    mo.Html(
        f'<div style="padding:40px 0 28px; border-bottom:2px solid {C["accent"]}; margin-bottom:36px;">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:10px;">'
        f'Current AI · Ecosystem Mapping · Data Audit</div>'
        f'<h1 style="font-family:{F["headline"]}; font-size:2.2rem; font-weight:400; '
        f'color:{C["ink"]}; margin:0 0 14px; line-height:1.05; letter-spacing:-0.025em;">'
        f'Query Framework · Tier Data Audit</h1>'
        f'<p style="font-family:{F["body"]}; font-size:1rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.5;">'
        f'Probing data availability across the 4-tier query framework. '
        f'What can we answer today, what needs supplementation, '
        f'and where are the critical gaps?</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_base_catalog(mo, pyoso_db_conn):
    df_catalog = mo.sql(
        f"""
        SELECT
          repo,
          category,
          CAST(stars AS DOUBLE) AS stars,
          CAST(contributors AS DOUBLE) AS contributors
        FROM currentai.catalog.goodailist_repos
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_catalog,)


@app.cell(hide_code=True)
def load_sbom_coverage(mo, pyoso_db_conn):
    df_sbom_coverage = mo.sql(
        f"""
        SELECT
          COUNT(DISTINCT s.dependent_artifact_namespace || '/' || s.dependent_artifact_name)
            AS ai_repos_with_sboms
        FROM oso.sboms_v0 s
        INNER JOIN currentai.catalog.goodailist_repos a
          ON s.dependent_artifact_namespace || '/' || s.dependent_artifact_name = a.repo
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_sbom_coverage,)


@app.cell(hide_code=True)
def load_dep_graph_stats(mo, pyoso_db_conn):
    df_dep_stats = mo.sql(
        f"""
        SELECT
          COUNT(*) AS total_edges,
          COUNT(CASE WHEN min_depth = 1 THEN 1 END) AS direct_edges,
          COUNT(CASE WHEN min_depth = 2 THEN 1 END) AS transitive_edges,
          COUNT(DISTINCT dependent_repo) AS dependent_repos,
          COUNT(DISTINCT dependency_repo) AS dependency_repos
        FROM currentai.scores.dependency_graph
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_dep_stats,)


@app.cell(hide_code=True)
def overview_stats(C, F, df_catalog, df_dep_stats, df_sbom_coverage, mo):
    _total_repos = len(df_catalog)
    _sbom_count = int(df_sbom_coverage["ai_repos_with_sboms"].iloc[0])
    _total_edges = int(df_dep_stats["total_edges"].iloc[0])
    _direct = int(df_dep_stats["direct_edges"].iloc[0])
    _transitive = int(df_dep_stats["transitive_edges"].iloc[0])
    _dep_repos = int(df_dep_stats["dependency_repos"].iloc[0])

    _section = mo.vstack([
        mo.Html(
            f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
            f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
            f'Overview</div>'
            f'<h2 style="font-family:{F["headline"]}; font-size:1.4rem; font-weight:500; '
            f'color:{C["ink"]}; margin:0 0 8px;">Data Coverage by Tier</h2>'
            f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
            f'margin:0 0 20px; line-height:1.5;">'
            f'Of {_total_repos:,} AI repos in our catalog, how much composition, '
            f'health, and fragility data can we extract from OSO today?</p>'
        ),
        mo.hstack([
            mo.stat(
                label="AI Repos",
                value=f"{_total_repos:,}",
                bordered=True,
                caption="base catalog (GoodAI + OSS Insights)",
            ),
            mo.stat(
                label="SBOM Coverage",
                value=f"{_sbom_count:,}",
                bordered=True,
                caption=f"{_sbom_count/_total_repos:.0%} of catalog has dependency data",
            ),
            mo.stat(
                label="Dependency Graph",
                value=f"{_total_edges:,}",
                bordered=True,
                caption=f"{_direct:,} direct + {_transitive:,} transitive edges",
            ),
            mo.stat(
                label="Foundation Repos",
                value=f"{_dep_repos:,}",
                bordered=True,
                caption="AI repos that others depend on",
            ),
        ], widths="equal", gap=1),
    ])
    _section
    return


@app.cell(hide_code=True)
def tier_summary_table(C, F, mo):
    _rows = [
        ("Tier 1", "Composition & Dependencies", "Partial",
         "SBOMs (6% coverage), package graphs, repo-to-repo deps. "
         "Missing: substitutability, integration cost, functional decomposition."),
        ("Tier 2", "Gap & Openness", "Partial",
         "OSAI gap map (41 subcats), GoodAI license field. "
         "Missing: per-repo openness audit, structured governance."),
        ("Tier 3", "Fragility & People", "Partial",
         "Contributor absence factor, funding tables (OC/Gitcoin), "
         "package maintainer data. Missing: truck factor, talent flow."),
        ("Tier 4", "Onboarding", "Not Started",
         "No data. Needs hackathon/program DB, learning pathways."),
    ]

    _html_rows = ""
    for _tier, _name, _status, _detail in _rows:
        if _status == "Not Started":
            _color = C["signal"]
        elif _status == "Partial":
            _color = C["warm"]
        else:
            _color = C["healthy"]
        _html_rows += (
            f'<tr>'
            f'<td style="font-family:{F["mono"]}; font-size:12px; font-weight:500; '
            f'padding:10px 12px;">{_tier}</td>'
            f'<td style="padding:10px 12px; font-weight:500;">{_name}</td>'
            f'<td style="padding:10px 12px;">'
            f'<span style="color:{_color}; font-weight:600;">{_status}</span></td>'
            f'<td style="padding:10px 12px; font-size:13px; color:{C["ink_2"]};">'
            f'{_detail}</td>'
            f'</tr>'
        )

    mo.Html(
        f'<table style="width:100%; border-collapse:collapse; font-family:{F["body"]}; '
        f'font-size:14px; margin-top:12px;">'
        f'<thead><tr style="border-bottom:2px solid {C["rule"]};">'
        f'<th style="text-align:left; padding:8px 12px; font-family:{F["mono"]}; '
        f'font-size:10px; color:{C["ink_3"]}; text-transform:uppercase; '
        f'letter-spacing:0.08em;">Tier</th>'
        f'<th style="text-align:left; padding:8px 12px; font-family:{F["mono"]}; '
        f'font-size:10px; color:{C["ink_3"]}; text-transform:uppercase; '
        f'letter-spacing:0.08em;">Focus</th>'
        f'<th style="text-align:left; padding:8px 12px; font-family:{F["mono"]}; '
        f'font-size:10px; color:{C["ink_3"]}; text-transform:uppercase; '
        f'letter-spacing:0.08em;">Status</th>'
        f'<th style="text-align:left; padding:8px 12px; font-family:{F["mono"]}; '
        f'font-size:10px; color:{C["ink_3"]}; text-transform:uppercase; '
        f'letter-spacing:0.08em;">Detail</th>'
        f'</tr></thead>'
        f'<tbody>{_html_rows}</tbody>'
        f'</table>'
    )
    return


@app.cell(hide_code=True)
def tier1_header(C, F, mo):
    mo.Html(
        f'<div style="margin-top:48px; padding-top:32px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Tier 1</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.4rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 8px;">Composition & Dependencies</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
        f'margin:0 0 20px; line-height:1.5;">'
        f'The hardest tier — and the one everything upstream depends on. '
        f'Can we build a dependency graph of the open-source AI stack from what OSO already has?</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_sbom_by_ecosystem(mo, pyoso_db_conn):
    df_sbom_ecosystems = mo.sql(
        f"""
        SELECT
          s.package_artifact_source AS ecosystem,
          COUNT(*) AS total_edges,
          COUNT(DISTINCT s.dependent_artifact_name) AS total_repos,
          COUNT(DISTINCT CASE
            WHEN a.repo IS NOT NULL THEN s.dependent_artifact_name
          END) AS ai_repos
        FROM oso.sboms_v0 s
        LEFT JOIN currentai.catalog.goodailist_repos a
          ON s.dependent_artifact_namespace || '/' || s.dependent_artifact_name = a.repo
        GROUP BY s.package_artifact_source
        ORDER BY total_edges DESC
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_sbom_ecosystems,)


@app.cell(hide_code=True)
def sbom_ecosystem_chart(C, CHART_LAYOUT, F, df_sbom_ecosystems, go, mo):
    _df = df_sbom_ecosystems.sort_values("total_edges", ascending=True)

    _fig = go.Figure()
    _fig.add_trace(go.Bar(
        y=_df["ecosystem"],
        x=_df["total_edges"],
        orientation="h",
        name="All repos",
        marker_color=C["accent"],
        hovertemplate="<b>%{y}</b><br>Total edges: %{x:,}<extra></extra>",
    ))
    _fig.add_trace(go.Bar(
        y=_df["ecosystem"],
        x=_df["ai_repos"],
        orientation="h",
        name="AI repos in catalog",
        marker_color=C["warm"],
        hovertemplate="<b>%{y}</b><br>AI repos: %{x:,}<extra></extra>",
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": 320, "barmode": "group"},
        xaxis=dict(
            title="Count (log scale)", type="log",
            showgrid=True, gridcolor=C["rule"],
        ),
        yaxis=dict(title="", showgrid=False),
    )

    mo.vstack([
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:24px 0 4px;">SBOM Coverage by Package Ecosystem</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">NPM dominates with 35M edges. PIP — the primary AI ecosystem — '
            f'has only 408K edges across 15K repos.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def sbom_coverage_stats(C, F, df_catalog, df_sbom_ecosystems, mo):
    _total_ai = len(df_catalog)
    _ai_with_sbom = int(df_sbom_ecosystems["ai_repos"].sum())
    _pip_row = df_sbom_ecosystems[df_sbom_ecosystems["ecosystem"] == "PIP"]
    _pip_ai = int(_pip_row["ai_repos"].iloc[0]) if len(_pip_row) > 0 else 0

    mo.vstack([
        mo.hstack([
            mo.stat(
                label="AI SBOM Coverage",
                value=f"{_ai_with_sbom/_total_ai:.0%}",
                bordered=True,
                caption=f"{_ai_with_sbom:,} of {_total_ai:,} repos",
            ),
            mo.stat(
                label="PIP AI Repos",
                value=f"{_pip_ai:,}",
                bordered=True,
                caption="Python package dependencies",
            ),
            mo.stat(
                label="Total SBOM Repos",
                value=f"{int(df_sbom_ecosystems['total_repos'].sum()):,}",
                bordered=True,
                caption="across all 7 package ecosystems",
            ),
        ], widths="equal", gap=1),
        mo.Html(
            f'<div style="background:{C["paper_2"]}; padding:14px 18px; border-radius:6px; '
            f'margin-top:12px; font-family:{F["body"]}; font-size:0.85rem; '
            f'color:{C["ink_2"]}; line-height:1.5;">'
            f'<strong style="color:{C["signal"]};">Key gap:</strong> '
            f'Most AI repos are Python-heavy, but PIP SBOM coverage in OSO is thin '
            f'compared to NPM. The 6% coverage rate means we can build a partial '
            f'dependency graph, but it skews toward repos that also publish JS/Rust packages.</div>'
        ),
    ])
    return


@app.cell(hide_code=True)
def load_foundation_repos(mo, pyoso_db_conn):
    df_foundation = mo.sql(
        f"""
        SELECT
          dependency_repo AS repo,
          dependency_category AS category,
          CAST(dependency_stars AS BIGINT) AS stars,
          COUNT(*) AS total_dependents,
          COUNT(CASE WHEN min_depth = 1 THEN 1 END) AS direct,
          COUNT(CASE WHEN min_depth = 2 THEN 1 END) AS transitive
        FROM currentai.scores.dependency_graph
        GROUP BY dependency_repo, dependency_category, dependency_stars
        ORDER BY total_dependents DESC
        LIMIT 40
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_foundation,)


@app.cell(hide_code=True)
def foundation_chart(C, CAT_COLORS, CHART_LAYOUT, F, df_foundation, go, mo):
    _df = df_foundation.head(20).sort_values("total_dependents", ascending=True)
    _colors = [CAT_COLORS.get(c, "#999") for c in _df["category"]]

    _fig = go.Figure()
    _fig.add_trace(go.Bar(
        y=_df["repo"],
        x=_df["direct"],
        orientation="h",
        name="Direct",
        marker_color=C["accent"],
        hovertemplate="<b>%{y}</b><br>Direct: %{x:,}<extra></extra>",
    ))
    _fig.add_trace(go.Bar(
        y=_df["repo"],
        x=_df["transitive"],
        orientation="h",
        name="Transitive",
        marker_color=C["warm"],
        hovertemplate="<b>%{y}</b><br>Transitive: %{x:,}<extra></extra>",
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": max(300, len(_df) * 28), "barmode": "stack"},
        xaxis=dict(
            title="AI repos that depend on this project",
            showgrid=True, gridcolor=C["rule"],
        ),
        yaxis=dict(title="", showgrid=False, tickfont=dict(size=11)),
    )

    mo.vstack([
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:32px 0 4px;">Foundation Projects</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">Top 20 AI repos by total dependents (direct + transitive). '
            f'Stacked bars show how much reach is direct vs one-hop transitive.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def hidden_pillars_chart(C, CHART_LAYOUT, F, df_foundation, go, mo):
    _df = df_foundation.copy()
    _df["transitive_ratio"] = _df["transitive"] / _df["total_dependents"]
    _pillars = _df[
        (_df["transitive_ratio"] > 0.7) & (_df["total_dependents"] >= 50)
    ].sort_values("total_dependents", ascending=True).tail(15)

    _fig = go.Figure(go.Bar(
        y=_pillars["repo"],
        x=_pillars["total_dependents"],
        orientation="h",
        marker_color=[
            C["signal"] if r > 0.9 else C["warm"]
            for r in _pillars["transitive_ratio"]
        ],
        text=[f'{r:.0%} transitive' for r in _pillars["transitive_ratio"]],
        textposition="inside",
        textfont=dict(size=10, color="white"),
        hovertemplate=(
            "<b>%{y}</b><br>"
            "Total dependents: %{x:,}<br>"
            "Stars: %{customdata:,}<extra></extra>"
        ),
        customdata=_pillars["stars"],
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": max(300, len(_pillars) * 28)},
        xaxis=dict(
            title="Total dependent AI repos",
            showgrid=True, gridcolor=C["rule"],
        ),
        yaxis=dict(title="", showgrid=False, tickfont=dict(size=11)),
    )

    mo.vstack([
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:32px 0 4px;">Hidden Pillars</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">Repos where &gt;70% of dependents are transitive — '
            f'invisible infrastructure that the stack depends on indirectly. '
            f'These are fragility hotspots: high downstream impact, low direct visibility.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def load_cross_category(mo, pyoso_db_conn):
    df_cross_cat = mo.sql(
        f"""
        SELECT
          dependent_category,
          dependency_category,
          COUNT(*) AS edge_count
        FROM currentai.scores.dependency_graph
        WHERE min_depth = 1
        GROUP BY dependent_category, dependency_category
        ORDER BY edge_count DESC
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_cross_cat,)


@app.cell(hide_code=True)
def cross_category_heatmap(C, CHART_LAYOUT, F, df_cross_cat, go, mo):
    _pivot = df_cross_cat.pivot_table(
        index="dependent_category",
        columns="dependency_category",
        values="edge_count",
        fill_value=0,
    )
    _cats = sorted(set(df_cross_cat["dependent_category"]) | set(df_cross_cat["dependency_category"]))
    _pivot = _pivot.reindex(index=_cats, columns=_cats, fill_value=0)

    _fig = go.Figure(go.Heatmap(
        z=_pivot.values,
        x=_pivot.columns.tolist(),
        y=_pivot.index.tolist(),
        colorscale=[
            [0, "white"],
            [0.3, C["paper_2"]],
            [0.6, C["warm"]],
            [1.0, C["accent"]],
        ],
        hovertemplate=(
            "Depends on: %{x}<br>"
            "Depended by: %{y}<br>"
            "Edges: %{z:,}<extra></extra>"
        ),
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": 420},
        xaxis=dict(title="Dependency (provides)", tickangle=35, tickfont=dict(size=10)),
        yaxis=dict(title="Dependent (consumes)", tickfont=dict(size=10)),
    )

    mo.vstack([
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:32px 0 4px;">Cross-Category Dependencies</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">Direct dependency flow between GoodAI categories. '
            f'Rows consume, columns provide. Darker = more dependency edges.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def explorer_dropdown(df_foundation, mo):
    _options = {r: r for r in df_foundation["repo"].tolist()}
    explorer_repo = mo.ui.dropdown(
        options=_options,
        value=df_foundation["repo"].iloc[0],
        label="Explore dependencies for:",
    )
    return (explorer_repo,)


@app.cell(hide_code=True)
def load_explorer_deps(explorer_repo, mo, pyoso_db_conn):
    _selected = explorer_repo.value
    df_explorer = mo.sql(
        f"""
        SELECT
          dependent_repo,
          dependent_category,
          min_depth
        FROM currentai.scores.dependency_graph
        WHERE dependency_repo = '{_selected}'
        ORDER BY min_depth, dependent_repo
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    df_explorer_provides = mo.sql(
        f"""
        SELECT
          dependency_repo,
          dependency_category,
          min_depth
        FROM currentai.scores.dependency_graph
        WHERE dependent_repo = '{_selected}'
        ORDER BY min_depth, dependency_repo
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return df_explorer, df_explorer_provides


@app.cell(hide_code=True)
def explorer_card(C, F, df_explorer, df_explorer_provides, explorer_repo, mo):
    _repo = explorer_repo.value
    _n_dependents = len(df_explorer)
    _n_direct = len(df_explorer[df_explorer["min_depth"] == 1])
    _n_deps = len(df_explorer_provides)
    _n_deps_direct = len(df_explorer_provides[df_explorer_provides["min_depth"] == 1])

    _card = mo.vstack([
        mo.Html(
            f'<div style="background:{C["paper_2"]}; padding:16px 20px; '
            f'border-radius:8px 8px 0 0; border-top:3px solid {C["accent"]};">'
            f'<div style="font-family:{F["mono"]}; font-size:13px; font-weight:500; '
            f'color:{C["ink"]};">{_repo}</div></div>'
        ),
        mo.hstack([
            mo.stat(
                label="Dependents",
                value=f"{_n_dependents:,}",
                bordered=True,
                caption=f"{_n_direct:,} direct",
            ),
            mo.stat(
                label="Dependencies",
                value=f"{_n_deps:,}",
                bordered=True,
                caption=f"{_n_deps_direct:,} direct",
            ),
        ], widths="equal", gap=1),
        mo.hstack([
            mo.vstack([
                mo.md(f"**Who depends on this** ({_n_dependents})"),
                mo.ui.table(df_explorer, selection=None),
            ]),
            mo.vstack([
                mo.md(f"**What this depends on** ({_n_deps})"),
                mo.ui.table(df_explorer_provides, selection=None),
            ]),
        ], widths="equal", gap=2),
    ])
    _card
    return


@app.cell(hide_code=True)
def tier1_gap_analysis(C, F, mo):
    mo.Html(
        f'<div style="margin-top:24px; background:{C["paper_2"]}; padding:20px 24px; '
        f'border-radius:8px; border-left:4px solid {C["signal"]};">'
        f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 12px;">Tier 1 Gap Analysis</h3>'
        f'<div style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_2"]}; line-height:1.6;">'
        f'<p><strong>What we have:</strong></p>'
        f'<ul style="margin:4px 0 12px;">'
        f'<li>Package-level dependencies for ~960 AI repos via SBOMs (6% coverage)</li>'
        f'<li>Transitive AI→AI dependency graph via <code>scores.dependency_graph</code> UDM '
        f'(~25K edges: direct + transitive to depth 2)</li>'
        f'<li>Package records via <code>entities.packages</code> UDM</li>'
        f'<li>Foundation project ranking with "hidden pillars" identification</li></ul>'
        f'<p><strong style="color:{C["signal"]};">What\'s missing:</strong></p>'
        f'<ul style="margin:4px 0 12px;">'
        f'<li><strong>SBOM coverage gap</strong> — 94% of AI repos have no SBOM. '
        f'PIP (Python) coverage is especially thin vs NPM.</li>'
        f'<li><strong>Substitutability matrix</strong> — We know what depends on what, '
        f'but not what could replace what. Needs functional equivalence mapping.</li>'
        f'<li><strong>Integration cost</strong> — No data on how hard it is to swap '
        f'components. Would need API surface analysis or community survey.</li>'
        f'<li><strong>Functional decomposition</strong> — Can\'t decompose closed products '
        f'(GPT-5, Claude) into open components. Needs "Kakashi" spec-level graph.</li></ul>'
        f'<p><strong>Recommended next step:</strong> Cross the dependency graph with '
        f'contributor absence factor and funding data to identify fragile foundation '
        f'projects — high transitive impact, low maintainer count.</p>'
        f'</div></div>'
    )
    return


@app.cell(hide_code=True)
def tier2_header(C, F, mo):
    mo.Html(
        f'<div style="margin-top:48px; padding-top:32px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Tier 2</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.4rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 8px;">Gap & Openness</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
        f'margin:0 0 20px; line-height:1.5;">'
        f'Diagnostic data — where is open source competitive, and how genuinely open are the projects?</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_license_data(mo, pyoso_db_conn):
    df_licenses = mo.sql(
        f"""
        SELECT
          r.license,
          COUNT(*) AS repo_count
        FROM currentai.catalog.goodailist_repos r
        WHERE r.license IS NOT NULL AND r.license != ''
        GROUP BY r.license
        ORDER BY repo_count DESC
        LIMIT 20
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_licenses,)


@app.cell(hide_code=True)
def load_license_coverage(mo, pyoso_db_conn):
    df_license_cov = mo.sql(
        f"""
        SELECT
          COUNT(*) AS total_repos,
          COUNT(CASE WHEN license IS NOT NULL AND license != '' THEN 1 END)
            AS has_license
        FROM currentai.catalog.goodailist_repos
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_license_cov,)


@app.cell(hide_code=True)
def tier2_license_chart(
    C,
    CHART_LAYOUT,
    F,
    df_license_cov,
    df_licenses,
    go,
    mo,
):
    _total = int(df_license_cov["total_repos"].iloc[0])
    _has = int(df_license_cov["has_license"].iloc[0])

    _df = df_licenses.head(15).sort_values("repo_count", ascending=True)

    _permissive = {"MIT License", "Apache License 2.0", "BSD 3-Clause License",
                   "BSD 2-Clause License", "ISC License", "Unlicense"}
    _colors = [
        C["healthy"] if lic in _permissive else C["warm"]
        for lic in _df["license"]
    ]

    _fig = go.Figure(go.Bar(
        y=_df["license"],
        x=_df["repo_count"],
        orientation="h",
        marker_color=_colors,
        hovertemplate="<b>%{y}</b><br>Repos: %{x:,}<extra></extra>",
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": max(300, len(_df) * 28)},
        xaxis=dict(title="Repo count", showgrid=True, gridcolor=C["rule"]),
        yaxis=dict(title="", showgrid=False, tickfont=dict(size=10)),
    )

    mo.vstack([
        mo.hstack([
            mo.stat(
                label="License Coverage",
                value=f"{_has/_total:.0%}",
                bordered=True,
                caption=f"{_has:,} of {_total:,} GoodAI repos",
            ),
            mo.stat(
                label="OSAI Gap Map",
                value="41 subcats",
                bordered=True,
                caption="10 dimensions scored 1-5",
            ),
            mo.stat(
                label="Per-Repo Openness",
                value="Not available",
                bordered=True,
                caption="weights/data/methodology audit needed",
            ),
        ], widths="equal", gap=1),
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:20px 0 4px;">License Distribution</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">Top 15 licenses across GoodAI repos. '
            f'<span style="color:{C["healthy"]};">Green</span> = permissive, '
            f'<span style="color:{C["warm"]};">amber</span> = copyleft/restricted.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def tier2_gap_note(C, F, mo):
    mo.Html(
        f'<div style="background:{C["paper_2"]}; padding:14px 18px; border-radius:6px; '
        f'margin-top:12px; font-family:{F["body"]}; font-size:0.85rem; '
        f'color:{C["ink_2"]}; line-height:1.5;">'
        f'<strong>Tier 2 gaps:</strong> '
        f'License data exists but is coarse (just the license string). '
        f'No structured openness audit — we can\'t distinguish "open weights + closed training data" '
        f'from "fully open." The OSAI gap map provides qualitative parity verdicts but not '
        f'per-repo scores. A governance classification (foundation vs corporate vs community) '
        f'would add significant value.</div>'
    )
    return


@app.cell(hide_code=True)
def tier3_header(C, F, mo):
    mo.Html(
        f'<div style="margin-top:48px; padding-top:32px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Tier 3</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.4rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 8px;">Fragility & People</h2>'
        f'<p style="font-family:{F["body"]}; font-size:0.95rem; color:{C["ink_2"]}; '
        f'margin:0 0 20px; line-height:1.5;">'
        f'What the map alone can\'t see — maintainer health, funding, and single points of failure.</p>'
        f'</div>'
    )
    return


@app.cell(hide_code=True)
def load_absence_factor(mo, pyoso_db_conn):
    df_absence = mo.sql(
        f"""
        SELECT
          CAST(caf.amount AS INTEGER) AS absence_factor,
          COUNT(*) AS artifact_count
        FROM oso.contributor_absence_factor_to_artifact_yearly caf
        WHERE caf.metrics_sample_date >= DATE('2025-01-01')
        GROUP BY CAST(caf.amount AS INTEGER)
        ORDER BY absence_factor
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_absence,)


@app.cell(hide_code=True)
def load_absence_ai_coverage(mo, pyoso_db_conn):
    df_absence_ai = mo.sql(
        f"""
        SELECT
          COUNT(DISTINCT caf.to_artifact_id) AS artifacts_with_absence,
          COUNT(DISTINCT CASE
            WHEN a.repo IS NOT NULL THEN caf.to_artifact_id
          END) AS ai_artifacts_with_absence
        FROM oso.contributor_absence_factor_to_artifact_yearly caf
        LEFT JOIN oso.artifacts_by_project_v1 abp
          ON caf.to_artifact_id = abp.artifact_id
        LEFT JOIN currentai.catalog.goodailist_repos a
          ON abp.artifact_namespace || '/' || abp.artifact_name = a.repo
        WHERE caf.metrics_sample_date >= DATE('2025-01-01')
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_absence_ai,)


@app.cell(hide_code=True)
def load_funding_coverage(mo, pyoso_db_conn):
    df_funding_cov = mo.sql(
        f"""
        SELECT
          COUNT(DISTINCT f.to_artifact_id) AS funded_artifacts,
          SUM(f.amount) AS total_funding
        FROM oso.funding_received_to_artifact_over_all_time f
        WHERE f.amount > 0
        """,
        output=False,
        engine=pyoso_db_conn,
    )
    return (df_funding_cov,)


@app.cell(hide_code=True)
def tier3_stats(
    C,
    CHART_LAYOUT,
    F,
    df_absence,
    df_absence_ai,
    df_funding_cov,
    go,
    mo,
):
    _total_absence = int(df_absence_ai["artifacts_with_absence"].iloc[0])
    _ai_absence = int(df_absence_ai["ai_artifacts_with_absence"].iloc[0])
    _funded = int(df_funding_cov["funded_artifacts"].iloc[0])
    _total_funding = float(df_funding_cov["total_funding"].iloc[0])

    _single_maintainer = int(
        df_absence[df_absence["absence_factor"] == 1]["artifact_count"].sum()
    ) if len(df_absence[df_absence["absence_factor"] == 1]) > 0 else 0
    _total_measured = int(df_absence["artifact_count"].sum())

    _fig = go.Figure(go.Bar(
        x=df_absence["absence_factor"],
        y=df_absence["artifact_count"],
        marker_color=[
            C["signal"] if af == 1 else C["warm"] if af <= 2 else C["healthy"]
            for af in df_absence["absence_factor"]
        ],
        hovertemplate=(
            "Absence factor: %{x}<br>"
            "Repos: %{y:,}<extra></extra>"
        ),
    ))
    _fig.update_layout(
        **{**CHART_LAYOUT, "height": 320},
        xaxis=dict(
            title="Contributor absence factor (min people to lose 50% of commits)",
            showgrid=False, dtick=1,
        ),
        yaxis=dict(
            title="Number of repos", showgrid=True, gridcolor=C["rule"],
        ),
    )

    mo.vstack([
        mo.hstack([
            mo.stat(
                label="Absence Factor Coverage",
                value=f"{_total_absence:,}",
                bordered=True,
                caption=f"repos with bus-factor data (2025)",
            ),
            mo.stat(
                label="AI Repos Matched",
                value=f"{_ai_absence:,}",
                bordered=True,
                caption="via artifact_id join to our catalog",
            ),
            mo.stat(
                label="Funded Artifacts",
                value=f"{_funded:,}",
                bordered=True,
                caption=f"${_total_funding/1e6:,.1f}M total (OC + Gitcoin)",
            ),
            mo.stat(
                label="Single-Maintainer",
                value=f"{_single_maintainer/_total_measured:.0%}" if _total_measured > 0 else "N/A",
                bordered=True,
                caption=f"{_single_maintainer:,} of {_total_measured:,} measured repos",
            ),
        ], widths="equal", gap=1),
        mo.Html(
            f'<h3 style="font-family:{F["headline"]}; font-size:1.1rem; font-weight:500; '
            f'color:{C["ink"]}; margin:20px 0 4px;">Contributor Absence Factor Distribution</h3>'
            f'<p style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
            f'margin:0 0 12px;">How many people would need to leave before 50% of commit '
            f'activity disappears? Factor = 1 means a single point of failure.</p>'
        ),
        mo.ui.plotly(_fig, config={"displayModeBar": False}),
    ])
    return


@app.cell(hide_code=True)
def tier3_gap_note(C, F, mo):
    mo.Html(
        f'<div style="background:{C["paper_2"]}; padding:14px 18px; border-radius:6px; '
        f'margin-top:12px; font-family:{F["body"]}; font-size:0.85rem; '
        f'color:{C["ink_2"]}; line-height:1.5;">'
        f'<strong>Tier 3 gaps:</strong> '
        f'Contributor absence factor exists but matching to our AI catalog via artifact_id '
        f'requires joining through oss-directory (most AI repos aren\'t OSO-tracked projects). '
        f'Funding data covers Open Collective and Gitcoin but misses corporate sponsorship, '
        f'venture funding, and government grants — likely the majority of AI project funding. '
        f'No talent flow data (researcher career trajectories).</div>'
    )
    return


@app.cell(hide_code=True)
def tier4_section(C, F, mo):
    mo.Html(
        f'<div style="margin-top:48px; padding-top:32px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:6px;">'
        f'Tier 4</div>'
        f'<h2 style="font-family:{F["headline"]}; font-size:1.4rem; font-weight:500; '
        f'color:{C["ink"]}; margin:0 0 8px;">Onboarding</h2>'
        f'<div style="background:{C["paper_2"]}; padding:20px 24px; border-radius:8px; '
        f'border-left:4px solid {C["signal"]}; margin-top:16px;">'
        f'<p style="font-family:{F["body"]}; font-size:0.9rem; color:{C["ink_2"]}; '
        f'margin:0; line-height:1.6;">'
        f'<strong style="color:{C["signal"]};">Not started.</strong> '
        f'Builder pathways — hackathons, learning resources, contribution on-ramps — '
        f'are not currently tracked in OSO or any of our external sources. '
        f'This tier requires manual curation or partnerships with '
        f'ecosystem programs (eg, Hugging Face courses, fast.ai, AI Alliance).</p>'
        f'</div></div>'
    )
    return


@app.cell(hide_code=True)
def methodology(C, F, mo):
    mo.Html(
        f'<div style="margin-top:48px; padding-top:24px; border-top:1px solid {C["rule"]};">'
        f'<div style="font-family:{F["mono"]}; font-size:11px; color:{C["ink_3"]}; '
        f'letter-spacing:0.1em; text-transform:uppercase; margin-bottom:12px;">'
        f'Methodology</div>'
        f'<div style="font-family:{F["body"]}; font-size:0.85rem; color:{C["ink_3"]}; '
        f'line-height:1.6;">'
        f'<p><strong>Base catalog:</strong> 15.4K AI repos from GoodAI List, '
        f'resolved in <code>entities.repos</code> UDM (daily refresh).</p>'
        f'<p><strong>Dependency data:</strong> OSO SBOMs (<code>oso.sboms_v0</code>) contain '
        f'39M package dependency edges across 80K repos. The <code>scores.dependency_graph</code> '
        f'UDM computes transitive closure (depth 2) of AI→AI dependencies from '
        f'<code>int_code_dependencies</code>, yielding 25.7K edges. '
        f'Coverage is uneven: NPM (51K repos), PIP (15K repos), Rust (9.5K repos).</p>'
        f'<p><strong>Bus factor proxy:</strong> <code>contributor_absence_factor_to_artifact_yearly</code> '
        f'measures the minimum number of people whose departure would eliminate 50% of commit activity. '
        f'Only available for repos tracked in oss-directory.</p>'
        f'<p><strong>Funding:</strong> Open Collective + Gitcoin grants via OSO event tables. '
        f'Does not include corporate sponsorship, VC, or government grants.</p>'
        f'<p><strong>License data:</strong> Self-reported license field from GoodAI List API. '
        f'Not validated against actual repo license files.</p>'
        f'<p style="margin-top:12px;"><strong>Sources:</strong> '
        f'<a href="https://goodai.com/list" style="color:{C["accent"]};">GoodAI List</a> · '
        f'<a href="https://ossinsight.io" style="color:{C["accent"]};">OSS Insights</a> · '
        f'<a href="https://docs.oso.xyz" style="color:{C["accent"]};">OSO Docs</a></p>'
        f'</div></div>'
    )
    return


if __name__ == "__main__":
    app.run()
